targets:
  $default:
    builders:
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: drmem_provider|lib/src/schema/drmem.graphql
          type_overrides:
            DateTimeUtc:
              name: DateTime
          custom_serializers:
            - import: "../date_serializer.dart"
              name: DateSerializer
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: drmem_provider|lib/src/schema/drmem.graphql
          type_overrides:
            DateTimeUtc:
              name: DateTime